sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: l9WEnjCa+xPyMkK2mXTHjohf4i/4rBs8/rZXT2Zwt0B5xXZ0FqfQwSEO3MXT9QNor/f/SW6VUsGDYS6ecACde0sSFlhgh3RMJW52uFFzVCto1f5kzWH4ZoL1Ekqp/uuPw+gLw9alzKpjtkQp5s2f+DNVL2W/Qpof3cHzYtSBpjZVFe2xjcukwOfR84m6PnnXGD8uNpW4wKfEvF6QV1yOvSVIfkLXZ2wrrGOF298KEchN2Likaq4sbpZculhJCtz8uZPsFVCuw+yu7OVnntWxN8u2kly+Jb5Ro8M1KbemKZqyZ54ZvncAKdY+vTyhhV6MMuuODQV+cgsEqOt4qbpmfhXUXM8HTf8xaK7AoDFnJDWVKBbq71LIzU4+fQA27sPY4LBt5ohKGsRo1jycOrIHbEt4LZGoRqvSbK71X5lTz/tKkXul1imoYJT/5EmTHQrIVrgSULTpK4fGdTje4aPydWJZNnPN9w/aAbpzaaHOCRVx9LRuV1F8wuFV+eRhnv03UuZH4XQIMwIHoiaz5ZfoRueKUKCevSk3K/Ig76ktMqHdYLPRr/KbhZlA6AYsciLavLr4X4hn6zSV4vIhlN4PIluoLJiHAsK1GvLiOy+nHsVjdwNXVuHDIAh6rVuHY6HUkJQ8lFpgKPGyjUaYep4ILdrP8E46e6ui4cEQAAJMRMY=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Mr.-Crewe-s-Career---Volume-1_3681
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy